development:
  clients:
    default:
      database: Plantlennial_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: Plantlennial_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: "mongodb+srv://nyheimhunter:Zc4vI0Gz6vCbBgyy@cluster0.ln11dja.mongodb.net/?retryWrites=true&w=majority"
      options:
        # Add any additional connection options here
